-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "cgstAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "igstAmount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "sgstAmount" INTEGER NOT NULL DEFAULT 0;
