import { DiscountType, Role } from "@prisma/client";
import { NextRequest } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { apiError, json } from "@/lib/http";
const schema = z.object({ code: z.string().trim().min(3).max(40).transform((value) => value.toUpperCase()), type: z.nativeEnum(DiscountType), value: z.number().int().positive(), minimumOrder: z.number().int().nonnegative().optional(), maximumDiscount: z.number().int().positive().optional(), expiresAt: z.string().datetime().optional(), usageLimit: z.number().int().positive().optional(), perCustomerLimit: z.number().int().positive().optional(), firstOrderOnly: z.boolean().default(false), scopeType: z.enum(["ORDER", "PRODUCT", "CATEGORY", "COLLECTION"]).default("ORDER"), scopeIds: z.array(z.string().cuid()).default([]) }).superRefine((value, context) => { if (value.scopeType !== "ORDER" && !value.scopeIds.length) context.addIssue({ code: z.ZodIssueCode.custom, path: ["scopeIds"], message: "Select at least one eligible item." }); });
export async function POST(request: NextRequest) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN]); const input = schema.parse(await request.json()); const coupon = await db.coupon.create({ data: { ...input, expiresAt: input.expiresAt ? new Date(input.expiresAt) : undefined } }); await db.auditLog.create({ data: { actorId: admin.sub, action: "COUPON_CREATED", entityType: "Coupon", entityId: coupon.id, after: { code: coupon.code } } }); return json(coupon, 201); } catch (error) { return apiError(error); } }
export async function PATCH(request: NextRequest) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN]); const input = z.object({ id: z.string().cuid(), isActive: z.boolean() }).parse(await request.json()); const coupon = await db.coupon.update({ where: { id: input.id }, data: { isActive: input.isActive } }); await db.auditLog.create({ data: { actorId: admin.sub, action: "COUPON_UPDATED", entityType: "Coupon", entityId: coupon.id, after: { isActive: coupon.isActive } } }); return json(coupon); } catch (error) { return apiError(error); } }
