import { afterAll, describe, expect, it } from "vitest";
import { db } from "../lib/db";
import { addCartItem } from "../lib/services/cart-service";
import { createOrder } from "../lib/services/order-service";
import { releaseExpiredReservations } from "../lib/services/reservation-service";
import { markPaymentSuccess } from "../lib/payments";

const createdUsers: string[] = [];
const createdProducts: string[] = [];
async function fixture(label: string) { const store = await db.store.findFirstOrThrow(); const suffix = `${label}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; const user = await db.user.create({ data: { email: `${suffix}@integration.local`, name: "Integration Customer", passwordHash: "test-only" } }); const product = await db.product.create({ data: { storeId: store.id, name: `Integration ${label}`, slug: suffix, sku: suffix.toUpperCase(), description: "Integration-only product used to verify the real commerce transaction flow.", status: "ACTIVE", basePrice: 100_000, taxRate: 18, variants: { create: { title: "Standard", sku: `${suffix}-VAR`.toUpperCase(), stock: 3 } } }, include: { variants: true } }); createdUsers.push(user.id); createdProducts.push(product.id); await addCartItem({ userId: user.id }, { productId: product.id, variantId: product.variants[0].id, quantity: 2 }); return { user, product, variant: product.variants[0] }; }
afterAll(async () => { await db.notification.deleteMany({ where: { userId: { in: createdUsers } } }); await db.order.deleteMany({ where: { userId: { in: createdUsers } } }); await db.cart.deleteMany({ where: { userId: { in: createdUsers } } }); await db.user.deleteMany({ where: { id: { in: createdUsers } } }); await db.product.deleteMany({ where: { id: { in: createdProducts } } }); await db.$disconnect(); });

describe("commerce database integration", () => {
  it("atomically creates an order, reserves stock, then restores it on expiry", async () => { const { user, variant } = await fixture("expiry"); const order = await createOrder({ userId: user.id }, { name: user.name, phone: "9876543210", line1: "1 Test Street", city: "Bengaluru", state: "Karnataka", pincode: "560001" }, "RAZORPAY", crypto.randomUUID()); expect(order.items).toHaveLength(1); expect(order.total).toBeGreaterThan(order.subtotal); expect((await db.productVariant.findUniqueOrThrow({ where: { id: variant.id } })).stock).toBe(1); await db.inventoryReservation.updateMany({ where: { orderId: order.id }, data: { expiresAt: new Date(Date.now() - 1000) } }); expect(await releaseExpiredReservations()).toContain(order.id); expect((await db.productVariant.findUniqueOrThrow({ where: { id: variant.id } })).stock).toBe(3); expect((await db.order.findUniqueOrThrow({ where: { id: order.id } })).status).toBe("CANCELLED"); });
  it("confirms a verified payment once and keeps webhook handling idempotent", async () => { const { user } = await fixture("payment"); const order = await createOrder({ userId: user.id }, { name: user.name, phone: "9876543210", line1: "2 Test Street", city: "Bengaluru", state: "Karnataka", pincode: "560001" }, "RAZORPAY", crypto.randomUUID()); const transactionId = `pay_test_${Date.now()}`; await markPaymentSuccess(order.payments[0].id, transactionId, { test: "verified" }); await markPaymentSuccess(order.payments[0].id, transactionId, { test: "duplicate" }); const payment = await db.payment.findUniqueOrThrow({ where: { id: order.payments[0].id }, include: { transactions: true, order: true } }); expect(payment.status).toBe("SUCCESS"); expect(payment.order.status).toBe("CONFIRMED"); expect(payment.transactions).toHaveLength(1); expect(await db.notification.count({ where: { userId: user.id, template: "PAYMENT_CONFIRMED" } })).toBe(1); });
});
