import { NextRequest } from "next/server";
import { z } from "zod";
import { indianPhone } from "@/lib/phone";
import { requireSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { apiError, AppError, json } from "@/lib/http";
const fields = z.object({ name: z.string().trim().min(2), phone: indianPhone, line1: z.string().min(4), line2: z.string().optional(), city: z.string().min(2), state: z.string().min(2), pincode: z.string().regex(/^\d{6}$/), isDefault: z.boolean().default(false) });
export async function GET(request: NextRequest) { try { const session = await requireSession(request); return json(await db.address.findMany({ where: { userId: session.sub }, orderBy: [{ isDefault: "desc" }, { id: "asc" }] })); } catch (error) { return apiError(error); } }
export async function POST(request: NextRequest) { try { const session = await requireSession(request); const input = fields.parse(await request.json()); const address = await db.$transaction(async (tx) => { if (input.isDefault) await tx.address.updateMany({ where: { userId: session.sub }, data: { isDefault: false } }); return tx.address.create({ data: { userId: session.sub, ...input } }); }); return json(address, 201); } catch (error) { return apiError(error); } }
export async function PATCH(request: NextRequest) { try { const session = await requireSession(request); const input = fields.partial().extend({ id: z.string().cuid() }).parse(await request.json()); const existing = await db.address.findFirst({ where: { id: input.id, userId: session.sub } }); if (!existing) throw new AppError(404, "Address not found."); const { id, ...data } = input; return json(await db.$transaction(async (tx) => { if (data.isDefault) await tx.address.updateMany({ where: { userId: session.sub }, data: { isDefault: false } }); return tx.address.update({ where: { id }, data }); })); } catch (error) { return apiError(error); } }
export async function DELETE(request: NextRequest) { try { const session = await requireSession(request); const { id } = z.object({ id: z.string().cuid() }).parse(await request.json()); await db.address.deleteMany({ where: { id, userId: session.sub } }); return json({ removed: true }); } catch (error) { return apiError(error); } }
