import bcrypt from "bcryptjs";
import { DiscountType, HomepageSectionType, Prisma, PrismaClient, ProductCondition, ProductStatus, Role } from "@prisma/client";

const db = new PrismaClient();
const image = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`;
const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

type DemoProduct = {
  name: string; sku: string; category: string; brand: string; condition: ProductCondition;
  basePrice: number; salePrice?: number; warrantyMonths: number; photo: string; description: string;
  specifications: Record<string, string>; variants: { title: string; suffix: string; stock: number; attributes?: Record<string, string>; price?: number; salePrice?: number }[];
  collections: string[];
};

const products: DemoProduct[] = [
  { name: "Apple iPhone 15", sku: "APL-IP15", category: "New Phones", brand: "Apple", condition: ProductCondition.NEW, basePrice: 6999900, salePrice: 6499900, warrantyMonths: 12, photo: image("photo-1695048133142-1a20484d2569"), description: "New iPhone 15 with Dynamic Island, USB-C and a bright Super Retina XDR display, supplied with official India warranty.", specifications: { Display: "6.1-inch OLED", Camera: "48MP main", Processor: "A16 Bionic", OS: "iOS", Warranty: "1 year" }, variants: [{ title: "128GB · Black", suffix: "128-BLK", stock: 8, attributes: { Storage: "128GB", Color: "Black", RAM: "6GB" } }, { title: "256GB · Blue", suffix: "256-BLU", stock: 5, price: 7999900, salePrice: 7499900, attributes: { Storage: "256GB", Color: "Blue", RAM: "6GB" } }], collections: ["New Arrivals", "Premium Phones"] },
  { name: "Samsung Galaxy S24 5G", sku: "SAM-S24", category: "New Phones", brand: "Samsung", condition: ProductCondition.NEW, basePrice: 7499900, salePrice: 6299900, warrantyMonths: 12, photo: image("photo-1610945265064-0e34e5519bbf"), description: "Compact Galaxy AI flagship with a vivid AMOLED display, versatile cameras and seven generations of software support.", specifications: { Display: "6.2-inch AMOLED", Camera: "50MP triple camera", Processor: "Exynos 2400", OS: "Android", Warranty: "1 year" }, variants: [{ title: "128GB · Onyx Black", suffix: "128-BLK", stock: 9 }, { title: "256GB · Marble Gray", suffix: "256-GRY", stock: 6, price: 7999900, salePrice: 6799900 }], collections: ["New Arrivals", "Premium Phones"] },
  { name: "OnePlus 12R 5G", sku: "ONE-12R", category: "New Phones", brand: "OnePlus", condition: ProductCondition.NEW, basePrice: 4299900, salePrice: 3899900, warrantyMonths: 12, photo: image("photo-1598327105666-5b89351aff97"), description: "Performance-focused 5G phone with a smooth AMOLED display, fast charging and generous memory.", specifications: { Display: "6.78-inch AMOLED", Battery: "5500mAh", Charging: "100W", OS: "OxygenOS" }, variants: [{ title: "8GB + 128GB · Cool Blue", suffix: "8-128-BLU", stock: 10 }, { title: "16GB + 256GB · Iron Gray", suffix: "16-256-GRY", stock: 7, price: 4599900, salePrice: 4199900 }], collections: ["New Arrivals", "Best Sellers"] },
  { name: "Redmi Note 13 Pro 5G", sku: "XMI-N13P", category: "New Phones", brand: "Xiaomi", condition: ProductCondition.NEW, basePrice: 2899900, salePrice: 2599900, warrantyMonths: 12, photo: image("photo-1605236453806-6ff36851218e"), description: "Feature-rich 5G phone with a 200MP camera, high-resolution AMOLED display and fast charging.", specifications: { Display: "1.5K AMOLED", Camera: "200MP", Battery: "5100mAh", Charging: "67W" }, variants: [{ title: "8GB + 128GB · Midnight Black", suffix: "8-128-BLK", stock: 14 }, { title: "8GB + 256GB · Coral Purple", suffix: "8-256-PUR", stock: 9, price: 3099900, salePrice: 2799900 }], collections: ["Best Sellers"] },
  { name: "Apple iPhone 13 Certified", sku: "APL-IP13-RFB", category: "Refurbished Phones", brand: "Apple", condition: ProductCondition.REFURBISHED, basePrice: 4299900, salePrice: 3699900, warrantyMonths: 6, photo: image("photo-1592750475338-74b7b21085ab"), description: "Certified refurbished iPhone 13 with documented inspection, minimum 85% battery health and six-month warranty.", specifications: { Grade: "Excellent", Display: "6.1-inch OLED", Battery: "Minimum 85%", Accessories: "Cable included" }, variants: [{ title: "128GB · Midnight · Excellent", suffix: "128-BLK-A", stock: 6 }, { title: "128GB · Blue · Good", suffix: "128-BLU-B", stock: 4, salePrice: 3499900 }], collections: ["Refurbished Deals", "Best Sellers"] },
  { name: "Samsung Galaxy S22 Certified", sku: "SAM-S22-RFB", category: "Refurbished Phones", brand: "Samsung", condition: ProductCondition.REFURBISHED, basePrice: 3899900, salePrice: 3199900, warrantyMonths: 6, photo: image("photo-1610945415295-d9bbf067e59c"), description: "Professionally tested Galaxy S22 with excellent display condition, clean software and warranty coverage.", specifications: { Grade: "Very Good", Display: "6.1-inch AMOLED", Battery: "Tested", Accessories: "Cable included" }, variants: [{ title: "128GB · Phantom Black", suffix: "128-BLK", stock: 5 }, { title: "256GB · Green", suffix: "256-GRN", stock: 3, price: 4199900, salePrice: 3499900 }], collections: ["Refurbished Deals"] },
  { name: "OnePlus 10 Pro Certified", sku: "ONE-10P-RFB", category: "Refurbished Phones", brand: "OnePlus", condition: ProductCondition.REFURBISHED, basePrice: 3499900, salePrice: 2899900, warrantyMonths: 6, photo: image("photo-1592286927505-1def25115558"), description: "Certified OnePlus flagship with tested cameras, battery and charging, graded for transparent cosmetic condition.", specifications: { Grade: "Good", RAM: "8GB", Storage: "128GB", Warranty: "6 months" }, variants: [{ title: "8GB + 128GB · Volcanic Black", suffix: "8-128-BLK", stock: 4 }], collections: ["Refurbished Deals", "Under ₹29,999"] },
  { name: "Apple iPhone 11 Pre-owned", sku: "APL-IP11-USED", category: "Used Phones", brand: "Apple", condition: ProductCondition.USED, basePrice: 2499900, salePrice: 2199900, warrantyMonths: 3, photo: image("photo-1574755393849-623942496936"), description: "Pre-owned iPhone 11 with visible condition grading, tested Face ID, cameras and battery, plus three-month warranty.", specifications: { Grade: "Good", Battery: "Minimum 80%", Screen: "Minor signs of use", Warranty: "3 months" }, variants: [{ title: "64GB · Black · Good", suffix: "64-BLK-B", stock: 5 }, { title: "128GB · White · Good", suffix: "128-WHT-B", stock: 3, price: 2699900, salePrice: 2399900 }], collections: ["Pre-owned Value", "Under ₹24,999"] },
  { name: "Realme GT Neo 3 Pre-owned", sku: "RLM-GTN3-USED", category: "Used Phones", brand: "Realme", condition: ProductCondition.USED, basePrice: 1999900, salePrice: 1699900, warrantyMonths: 3, photo: image("photo-1565849904461-04a58ad377e0"), description: "Performance phone in good pre-owned condition with fast charging and all essential functions verified.", specifications: { Grade: "Good", RAM: "8GB", Storage: "128GB", Charging: "80W" }, variants: [{ title: "8GB + 128GB · Nitro Blue", suffix: "8-128-BLU", stock: 6 }], collections: ["Pre-owned Value", "Under ₹24,999"] },
  { name: "boAt Airdopes 141", sku: "BOAT-AD141", category: "Earphones", brand: "boAt", condition: ProductCondition.NEW, basePrice: 449900, salePrice: 129900, warrantyMonths: 12, photo: image("photo-1606220945770-b5b6c2c55bf1"), description: "Everyday true wireless earbuds with long playback, low-latency mode and USB-C charging.", specifications: { Type: "True wireless", Playback: "Up to 42 hours", Charging: "USB-C", Warranty: "1 year" }, variants: [{ title: "Bold Black", suffix: "BLK", stock: 35 }, { title: "Cyan Cider", suffix: "CYN", stock: 18 }], collections: ["Under ₹1,999", "Best Sellers"] },
  { name: "Sony WF-C700N", sku: "SON-WFC700N", category: "Earphones", brand: "Sony", condition: ProductCondition.NEW, basePrice: 1299000, salePrice: 799900, warrantyMonths: 12, photo: image("photo-1590658268037-6bf12165a8df"), description: "Compact noise-cancelling earbuds with balanced sound, multipoint connectivity and comfortable fit.", specifications: { Type: "True wireless", Feature: "Noise cancelling", Battery: "Up to 20 hours", Warranty: "1 year" }, variants: [{ title: "Black", suffix: "BLK", stock: 12 }, { title: "White", suffix: "WHT", stock: 8 }], collections: ["Premium Audio"] },
  { name: "Sony WH-CH720N", sku: "SON-CH720N", category: "Headphones", brand: "Sony", condition: ProductCondition.NEW, basePrice: 1499000, salePrice: 999900, warrantyMonths: 12, photo: image("photo-1546435770-a3e426bf472b"), description: "Lightweight wireless noise-cancelling headphones for focused commutes, calls and long listening sessions.", specifications: { Type: "Over-ear wireless", Battery: "Up to 35 hours", Feature: "Active noise cancelling", Warranty: "1 year" }, variants: [{ title: "Black", suffix: "BLK", stock: 12 }, { title: "Blue", suffix: "BLU", stock: 7 }], collections: ["Premium Audio", "Best Sellers"] },
  { name: "JBL Tune 770NC", sku: "JBL-T770NC", category: "Headphones", brand: "JBL", condition: ProductCondition.NEW, basePrice: 999900, salePrice: 599900, warrantyMonths: 12, photo: image("photo-1583394838336-acd977736f90"), description: "Wireless over-ear headphones with adaptive noise cancelling, JBL Pure Bass and multi-device connection.", specifications: { Type: "Over-ear", Battery: "Up to 70 hours", Feature: "Adaptive ANC", Warranty: "1 year" }, variants: [{ title: "Black", suffix: "BLK", stock: 15 }], collections: ["Premium Audio"] },
  { name: "JBL Flip 6 Portable Speaker", sku: "JBL-FLIP6", category: "Speakers", brand: "JBL", condition: ProductCondition.NEW, basePrice: 1499900, salePrice: 1099900, warrantyMonths: 12, photo: image("photo-1608043152269-423dbba4e7e1"), description: "Waterproof portable Bluetooth speaker with bold sound and durable outdoor-ready construction.", specifications: { Output: "30W", Rating: "IP67", Playback: "Up to 12 hours", Warranty: "1 year" }, variants: [{ title: "Black", suffix: "BLK", stock: 11 }, { title: "Blue", suffix: "BLU", stock: 6 }], collections: ["Premium Audio", "Weekend Deals"] },
  { name: "boAt Stone 352", sku: "BOAT-ST352", category: "Speakers", brand: "boAt", condition: ProductCondition.NEW, basePrice: 349900, salePrice: 169900, warrantyMonths: 12, photo: image("photo-1589003077984-894e133dabab"), description: "Compact Bluetooth speaker with punchy output, water resistance and portable all-day playback.", specifications: { Output: "10W", Rating: "IPX7", Playback: "Up to 12 hours", Warranty: "1 year" }, variants: [{ title: "Raging Black", suffix: "BLK", stock: 24 }], collections: ["Under ₹1,999", "Weekend Deals"] },
  { name: "Samsung 25W USB-C Charger", sku: "SAM-25W-CHG", category: "Chargers", brand: "Samsung", condition: ProductCondition.NEW, basePrice: 199900, salePrice: 129900, warrantyMonths: 6, photo: image("photo-1583863788434-e58a36330cf0"), description: "Compact Power Delivery wall charger suitable for supported Galaxy phones and USB-C devices.", specifications: { Output: "25W", Port: "USB-C", Standard: "PD/PPS", Cable: "Not included" }, variants: [{ title: "Black", suffix: "BLK", stock: 40 }, { title: "White", suffix: "WHT", stock: 32 }], collections: ["Mobile Essentials", "Under ₹1,999"] },
  { name: "Portronics Adapto 70 GaN Charger", sku: "POR-GAN70", category: "Chargers", brand: "Portronics", condition: ProductCondition.NEW, basePrice: 499900, salePrice: 299900, warrantyMonths: 12, photo: image("photo-1628815113969-0487917fc6a7"), description: "Multi-port GaN fast charger for laptops, tablets and phones with compact travel-friendly design.", specifications: { Output: "70W", Ports: "2 USB-C + USB-A", Technology: "GaN", Warranty: "1 year" }, variants: [{ title: "Black", suffix: "BLK", stock: 19 }], collections: ["Mobile Essentials"] },
  { name: "Apple USB-C to USB-C Cable", sku: "APL-C2C-1M", category: "USB Cables", brand: "Apple", condition: ProductCondition.NEW, basePrice: 190000, salePrice: 159900, warrantyMonths: 6, photo: image("photo-1615526675159-e248c3021d3f"), description: "One-metre woven USB-C charging cable for compatible iPhone, iPad, Mac and USB-C power adapters.", specifications: { Length: "1 metre", Connector: "USB-C to USB-C", Charging: "Up to 60W" }, variants: [{ title: "1m · White", suffix: "1M-WHT", stock: 28 }], collections: ["Mobile Essentials", "Under ₹1,999"] },
  { name: "boAt Type-C Fast Charging Cable", sku: "BOAT-C2C-15", category: "USB Cables", brand: "boAt", condition: ProductCondition.NEW, basePrice: 99900, salePrice: 39900, warrantyMonths: 12, photo: image("photo-1615526675159-e248c3021d3f"), description: "Braided everyday USB-C cable with fast charging support and reinforced connectors.", specifications: { Length: "1.5 metres", Connector: "USB-C to USB-C", Material: "Braided" }, variants: [{ title: "1.5m · Black", suffix: "15M-BLK", stock: 55 }], collections: ["Under ₹999", "Mobile Essentials"] },
  { name: "Twelve South USB-C Multiport Adapter", sku: "TS-MULTI7", category: "Adapters", brand: "Twelve South", condition: ProductCondition.NEW, basePrice: 699900, salePrice: 499900, warrantyMonths: 12, photo: image("photo-1625842268584-8f3296236761"), description: "Seven-port USB-C hub for laptops with HDMI, card reader, USB and pass-through charging.", specifications: { Ports: "7", Video: "4K HDMI", Charging: "100W pass-through", Body: "Aluminium" }, variants: [{ title: "Space Gray", suffix: "GRY", stock: 10 }], collections: ["Work From Anywhere"] },
  { name: "boAt 20,000mAh Power Bank", sku: "BOAT-PB20", category: "Power Banks", brand: "boAt", condition: ProductCondition.NEW, basePrice: 249900, salePrice: 169900, warrantyMonths: 12, photo: image("photo-1609592424824-18d3e3e7e7af"), description: "High-capacity USB-C power bank with dual output charging for workdays, trips and everyday backup.", specifications: { Capacity: "20,000mAh", Ports: "USB-A + USB-C", Charging: "22.5W", Warranty: "1 year" }, variants: [{ title: "20,000mAh · Black", suffix: "BLK", stock: 30 }], collections: ["Mobile Essentials", "Weekend Deals"] },
  { name: "Ambrane 10,000mAh MagSafe Power Bank", sku: "AMB-MAG10", category: "Power Banks", brand: "Ambrane", condition: ProductCondition.NEW, basePrice: 349900, salePrice: 229900, warrantyMonths: 12, photo: image("photo-1622434641406-a158123450f9"), description: "Magnetic wireless power bank with USB-C fast charging and a compact travel-friendly body.", specifications: { Capacity: "10,000mAh", Wireless: "15W", Wired: "20W USB-C", Warranty: "1 year" }, variants: [{ title: "Black", suffix: "BLK", stock: 16 }], collections: ["Mobile Essentials"] },
  { name: "Apple Watch SE GPS", sku: "APL-WSE", category: "Smart Watches", brand: "Apple", condition: ProductCondition.NEW, basePrice: 2990000, salePrice: 2690000, warrantyMonths: 12, photo: image("photo-1434494878577-86c23bcb06b9"), description: "Essential Apple Watch fitness, safety and connectivity features in a lightweight aluminium case.", specifications: { Case: "40mm", Connectivity: "GPS", Water: "50m resistant", Warranty: "1 year" }, variants: [{ title: "40mm · Midnight", suffix: "40-MID", stock: 8 }, { title: "44mm · Starlight", suffix: "44-STR", stock: 5, price: 3290000, salePrice: 2990000 }], collections: ["New Arrivals", "Premium Wearables"] },
  { name: "Samsung Galaxy Watch6", sku: "SAM-GW6", category: "Smart Watches", brand: "Samsung", condition: ProductCondition.NEW, basePrice: 3299900, salePrice: 1899900, warrantyMonths: 12, photo: image("photo-1523275335684-37898b6baf30"), description: "Wear OS smartwatch with health tracking, bright display and seamless Galaxy ecosystem integration.", specifications: { Case: "40mm", Connectivity: "Bluetooth", OS: "Wear OS", Warranty: "1 year" }, variants: [{ title: "40mm · Graphite", suffix: "40-GRA", stock: 9 }], collections: ["Premium Wearables", "Weekend Deals"] },
  { name: "Logitech K380 Bluetooth Keyboard", sku: "LOG-K380", category: "Computer Accessories", brand: "Logitech", condition: ProductCondition.NEW, basePrice: 399500, salePrice: 299500, warrantyMonths: 12, photo: image("photo-1587829741301-dc798b83add3"), description: "Compact multi-device Bluetooth keyboard for Windows, macOS, ChromeOS, Android and iPadOS.", specifications: { Connection: "Bluetooth", Devices: "Up to 3", Battery: "Up to 24 months", Warranty: "1 year" }, variants: [{ title: "Graphite", suffix: "GRA", stock: 18 }, { title: "Off White", suffix: "WHT", stock: 8 }], collections: ["Work From Anywhere"] },
  { name: "Logitech M331 Silent Mouse", sku: "LOG-M331", category: "Computer Accessories", brand: "Logitech", condition: ProductCondition.NEW, basePrice: 149500, salePrice: 109500, warrantyMonths: 12, photo: image("photo-1527814050087-3793815479db"), description: "Quiet wireless mouse with reliable tracking, comfortable shape and long battery life.", specifications: { Connection: "2.4GHz USB", Buttons: "3", Battery: "Up to 24 months", Warranty: "1 year" }, variants: [{ title: "Black", suffix: "BLK", stock: 26 }], collections: ["Work From Anywhere", "Under ₹1,999"] },
  { name: "Spigen iPhone 15 Rugged Armor Case", sku: "SPG-IP15-RA", category: "Mobile Accessories", brand: "Spigen", condition: ProductCondition.NEW, basePrice: 199900, salePrice: 129900, warrantyMonths: 6, photo: image("photo-1601593346740-925612772716"), description: "Slim protective TPU case with raised edges and textured grip for iPhone 15.", specifications: { Compatibility: "iPhone 15", Material: "TPU", Protection: "Air Cushion corners" }, variants: [{ title: "Matte Black", suffix: "BLK", stock: 34 }], collections: ["Mobile Essentials", "Under ₹1,999"] },
  { name: "Portronics Mobile Desk Stand", sku: "POR-MOBSTAND", category: "Mobile Accessories", brand: "Portronics", condition: ProductCondition.NEW, basePrice: 129900, salePrice: 69900, warrantyMonths: 6, photo: image("photo-1587033411391-5d9e51cce126"), description: "Adjustable foldable phone stand for desks, video calls, recipes and hands-free viewing.", specifications: { Material: "Aluminium", Adjustment: "Height and angle", Compatibility: "Most phones" }, variants: [{ title: "Silver", suffix: "SLV", stock: 40 }], collections: ["Under ₹999", "Work From Anywhere"] },
  { name: "Amazon Fire TV Stick HD", sku: "AMZ-FTV-HD", category: "Other Electronics", brand: "Amazon", condition: ProductCondition.NEW, basePrice: 499900, salePrice: 349900, warrantyMonths: 12, photo: image("photo-1593359677879-a4bb92f829d1"), description: "Compact streaming device with Alexa voice remote and access to popular entertainment apps.", specifications: { Resolution: "Full HD", Remote: "Alexa Voice Remote", Connectivity: "Dual-band Wi-Fi" }, variants: [{ title: "Fire TV Stick HD", suffix: "STD", stock: 13 }], collections: ["Weekend Deals"] },
];

async function main() {
  const store = await db.store.upsert({ where: { slug: "refurbshield" }, update: { name: "RefurbShield" }, create: { name: "RefurbShield", slug: "refurbshield" } });
  const admin = await db.user.upsert({ where: { email: "admin@refurbshield.local" }, update: {}, create: { name: "RefurbShield Admin", email: "admin@refurbshield.local", passwordHash: await bcrypt.hash("ChangeMe123!", 12), role: Role.SUPER_ADMIN } });
  await db.seller.upsert({ where: { storeId_slug: { storeId: store.id, slug: "refurbshield-direct" } }, update: {}, create: { storeId: store.id, name: "RefurbShield Direct", slug: "refurbshield-direct" } });

  const root = await db.category.upsert({ where: { storeId_slug: { storeId: store.id, slug: "electronics" } }, update: {}, create: { storeId: store.id, name: "Electronics", slug: "electronics", position: 0 } });
  const categoryNames = ["New Phones", "Refurbished Phones", "Used Phones", "Earphones", "Headphones", "Speakers", "Chargers", "USB Cables", "Adapters", "Power Banks", "Smart Watches", "Computer Accessories", "Mobile Accessories", "Other Electronics"];
  const categoryRows = await Promise.all(categoryNames.map((name, position) => db.category.upsert({ where: { storeId_slug: { storeId: store.id, slug: slugify(name) } }, update: { parentId: root.id, position: position + 1 }, create: { storeId: store.id, parentId: root.id, name, slug: slugify(name), position: position + 1 } })));
  const brandNames = ["Apple", "Samsung", "OnePlus", "Xiaomi", "Realme", "Sony", "JBL", "boAt", "Portronics", "Twelve South", "Ambrane", "Logitech", "Spigen", "Amazon"];
  const brandRows = await Promise.all(brandNames.map((name) => db.brand.upsert({ where: { storeId_slug: { storeId: store.id, slug: slugify(name) } }, update: {}, create: { storeId: store.id, name, slug: slugify(name), description: `${name} products sold through RefurbShield.` } })));
  const collectionNames = [...new Set(products.flatMap((item) => item.collections))];
  const collectionRows = await Promise.all(collectionNames.map((name) => db.collection.upsert({ where: { storeId_slug: { storeId: store.id, slug: slugify(name) } }, update: {}, create: { storeId: store.id, name, slug: slugify(name), description: `Demo collection: ${name}` } })));
  const categoryId = (name: string) => categoryRows.find((item) => item.name === name)!.id;
  const brandId = (name: string) => brandRows.find((item) => item.name === name)!.id;
  const collectionId = (name: string) => collectionRows.find((item) => item.name === name)!.id;
  const seller = await db.seller.findUniqueOrThrow({ where: { storeId_slug: { storeId: store.id, slug: "refurbshield-direct" } } });

  for (const item of products) {
    const product = await db.product.upsert({
      where: { sku: item.sku },
      update: { name: item.name, description: item.description, basePrice: item.basePrice, salePrice: item.salePrice, categoryId: categoryId(item.category), brandId: brandId(item.brand), condition: item.condition, warrantyMonths: item.warrantyMonths, specifications: item.specifications, status: ProductStatus.ACTIVE, tags: [slugify(item.category), slugify(item.brand), item.condition.toLowerCase()], grade: item.specifications.Grade, whatsIncluded: item.specifications.Accessories ?? "Product and charging cable where specified." },
      create: { storeId: store.id, sellerId: seller.id, name: item.name, slug: slugify(item.name), sku: item.sku, description: item.description, condition: item.condition, status: ProductStatus.ACTIVE, basePrice: item.basePrice, salePrice: item.salePrice, categoryId: categoryId(item.category), brandId: brandId(item.brand), warrantyMonths: item.warrantyMonths, specifications: item.specifications, tags: [slugify(item.category), slugify(item.brand), item.condition.toLowerCase()], grade: item.specifications.Grade, whatsIncluded: item.specifications.Accessories ?? "Product and charging cable where specified." },
    });
    const existingImage = await db.productImage.findFirst({ where: { productId: product.id } });
    if (!existingImage) await db.productImage.create({ data: { productId: product.id, url: item.photo, alt: item.name } });
    for (const variantInput of item.variants) {
      const sku = `${item.sku}-${variantInput.suffix}`;
      const variant = await db.productVariant.upsert({ where: { sku }, update: { attributes: variantInput.attributes as Prisma.InputJsonValue | undefined }, create: { productId: product.id, title: variantInput.title, sku, stock: variantInput.stock, price: variantInput.price, salePrice: variantInput.salePrice, attributes: variantInput.attributes as Prisma.InputJsonValue | undefined } });
      await db.inventoryTransaction.upsert({ where: { id: `seed-${variant.id}` }, update: {}, create: { id: `seed-${variant.id}`, variantId: variant.id, quantityDelta: variantInput.stock, previousStock: 0, resultingStock: variantInput.stock, reason: "INITIAL_STOCK", actorId: admin.id, reference: "DEMO_SEED" } });
      if ((item.condition === ProductCondition.REFURBISHED || item.condition === ProductCondition.USED) && item.category.includes("Phones")) await db.sensitiveDeviceInformation.upsert({ where: { variantId: variant.id }, update: {}, create: { variantId: variant.id, batteryHealth: item.condition === ProductCondition.REFURBISHED ? 87 : 82, deviceCondition: item.specifications.Grade ?? "Good", screenCondition: "Inspected demo condition", bodyCondition: "Inspected demo condition", accessoriesIncluded: item.specifications.Accessories ?? "Charging cable", activationStatus: "Ready for activation", refurbishmentDetails: "Demo record. Replace with the unit-specific inspection report before sale.", repairHistory: "Demo record. Device-specific history must be entered by an authorised admin before sale." } });
    }
    for (const collection of item.collections) await db.productCollection.upsert({ where: { productId_collectionId: { productId: product.id, collectionId: collectionId(collection) } }, update: {}, create: { productId: product.id, collectionId: collectionId(collection) } });
  }

  await db.storeSettings.upsert({ where: { storeId: store.id }, update: { paymentConfig: { razorpayEnabled: true, phonePeEnabled: false, snapmitEnabled: false, sandboxMode: true } }, create: { storeId: store.id, supportEmail: "support@refurbshield.example", supportPhone: "+91 90000 00000", address: { city: "Bengaluru", state: "Karnataka", country: "India" }, defaultTaxRate: 18, freeShippingThreshold: 49900, returnDays: 7, paymentConfig: { razorpayEnabled: true, phonePeEnabled: false, snapmitEnabled: false, sandboxMode: true } } });
  await db.shippingRule.upsert({ where: { id: "demo-standard-shipping" }, update: {}, create: { id: "demo-standard-shipping", storeId: store.id, name: "Standard India Delivery", states: [], pincodes: [], charge: 9900, freeShippingThreshold: 49900, estimatedDaysMin: 3, estimatedDaysMax: 7 } });
  await db.taxRule.upsert({ where: { id: "demo-india-gst" }, update: { rate: 18, homeState: "Karnataka", isActive: true }, create: { id: "demo-india-gst", storeId: store.id, name: "Standard electronics GST", rate: 18, homeState: "Karnataka", isActive: true } });
  await db.coupon.upsert({ where: { code: "WELCOME10" }, update: {}, create: { code: "WELCOME10", type: DiscountType.PERCENTAGE, value: 10, minimumOrder: 99900, maximumDiscount: 50000, firstOrderOnly: true, perCustomerLimit: 1, usageLimit: 1000 } });
  await db.coupon.upsert({ where: { code: "ACCESSORY200" }, update: {}, create: { code: "ACCESSORY200", type: DiscountType.FIXED, value: 20000, minimumOrder: 149900, maximumDiscount: 20000, scopeType: "CATEGORY", scopeIds: categoryNames.filter((name) => name.includes("Accessories")).map(categoryId) } });
  const homepageSections = [{ type: HomepageSectionType.HERO, title: "CERTIFIED TECH, CLEARLY PRICED", subtitle: "New, refurbished and pre-owned electronics with honest grades and warranty coverage." }, { type: HomepageSectionType.CATEGORIES, title: "Shop every essential" }, { type: HomepageSectionType.FEATURED_PRODUCTS, title: "Worth a closer look" }, { type: HomepageSectionType.COLLECTION, title: "Curated deals" }, { type: HomepageSectionType.BRANDS, title: "Brands people ask for" }, { type: HomepageSectionType.TRUST, title: "No guesswork. Just good gear." }];
  for (const [position, section] of homepageSections.entries()) { const existing = await db.homepageSection.findFirst({ where: { storeId: store.id, type: section.type } }); if (existing) await db.homepageSection.update({ where: { id: existing.id }, data: { position, title: section.title, subtitle: section.subtitle, isVisible: true } }); else await db.homepageSection.create({ data: { storeId: store.id, ...section, position, isVisible: true } }); }
  await db.homepageBanner.upsert({ where: { id: "demo-hero-banner" }, update: {}, create: { id: "demo-hero-banner", storeId: store.id, title: "Smart electronics, seriously checked", subtitle: "Demo storefront banner", imageUrl: image("photo-1598327105666-5b89351aff97"), linkUrl: "/products", isVisible: true } });
}

main().then(() => db.$disconnect()).catch(async (error) => { console.error(error); await db.$disconnect(); process.exit(1); });
