import { Role } from "@prisma/client";
import crypto from "node:crypto";
import { NextRequest } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { apiError, AppError, json } from "@/lib/http";

function encryptionKey() { const secret = process.env.DEVICE_DATA_ENCRYPTION_KEY; if (!secret || secret.length < 32) throw new AppError(503, "DEVICE_DATA_ENCRYPTION_KEY must be configured before storing IMEI data."); return crypto.createHash("sha256").update(secret).digest(); }
function encrypt(value: string) { const iv = crypto.randomBytes(12); const cipher = crypto.createCipheriv("aes-256-gcm", encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64")}.${cipher.getAuthTag().toString("base64")}.${encrypted.toString("base64")}`; }
function decrypt(value: string) { const [iv, tag, encrypted] = value.split("."); const decipher = crypto.createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(iv, "base64")); decipher.setAuthTag(Buffer.from(tag, "base64")); return Buffer.concat([decipher.update(Buffer.from(encrypted, "base64")), decipher.final()]).toString("utf8"); }
const schema = z.object({ variantId: z.string().cuid(), imei: z.string().regex(/^\d{15}$/).optional().or(z.literal("")), batteryHealth: z.number().int().min(0).max(100).optional(), repairHistory: z.string().max(4000).optional(), deviceCondition: z.string().max(200).optional(), screenCondition: z.string().max(200).optional(), bodyCondition: z.string().max(200).optional(), accessoriesIncluded: z.string().max(500).optional(), refurbishmentDetails: z.string().max(4000).optional(), activationStatus: z.string().max(100).optional() });
export async function GET(request: NextRequest, context: { params: Promise<{ id: string }> }) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN, Role.PRODUCT_MANAGER]); const productId = (await context.params).id; const records = await db.sensitiveDeviceInformation.findMany({ where: { variant: { productId } }, include: { variant: { select: { id: true, title: true, sku: true } } } }); await db.auditLog.create({ data: { actorId: admin.sub, action: "SENSITIVE_DEVICE_INFORMATION_ACCESSED", entityType: "Product", entityId: productId } }); return json(records.map((record) => ({ ...record, imei: record.imeiEncrypted ? decrypt(record.imeiEncrypted) : null, imeiEncrypted: undefined }))); } catch (error) { return apiError(error); } }
export async function PUT(request: NextRequest, context: { params: Promise<{ id: string }> }) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN, Role.PRODUCT_MANAGER]); const productId = (await context.params).id; const input = schema.parse(await request.json()); const variant = await db.productVariant.findFirst({ where: { id: input.variantId, productId } }); if (!variant) throw new AppError(404, "Variant not found on this product."); const record = await db.sensitiveDeviceInformation.upsert({ where: { variantId: input.variantId }, update: { imeiEncrypted: input.imei ? encrypt(input.imei) : undefined, batteryHealth: input.batteryHealth, repairHistory: input.repairHistory, deviceCondition: input.deviceCondition, screenCondition: input.screenCondition, bodyCondition: input.bodyCondition, accessoriesIncluded: input.accessoriesIncluded, refurbishmentDetails: input.refurbishmentDetails, activationStatus: input.activationStatus }, create: { variantId: input.variantId, imeiEncrypted: input.imei ? encrypt(input.imei) : undefined, batteryHealth: input.batteryHealth, repairHistory: input.repairHistory, deviceCondition: input.deviceCondition, screenCondition: input.screenCondition, bodyCondition: input.bodyCondition, accessoriesIncluded: input.accessoriesIncluded, refurbishmentDetails: input.refurbishmentDetails, activationStatus: input.activationStatus } }); await db.auditLog.create({ data: { actorId: admin.sub, action: "SENSITIVE_DEVICE_INFORMATION_UPDATED", entityType: "ProductVariant", entityId: variant.id } }); return json({ ...record, imeiEncrypted: undefined }); } catch (error) { return apiError(error); } }
