import Link from "next/link";
import { HomepageSectionType } from "@prisma/client";
import { ProductCard } from "@/components/store/product-card";
import { db } from "@/lib/db";
import { listProducts } from "@/lib/catalog";
export const dynamic = "force-dynamic";
export default async function Home() {
  const now = new Date();
  const [store, sections, banners, featured, refurbished, categories, brands, collections] = await Promise.all([
    db.store.findFirst({ include: { settings: true } }),
    db.homepageSection.findMany({ where: { isVisible: true }, orderBy: { position: "asc" } }),
    db.homepageBanner.findMany({ where: { isVisible: true, AND: [{ OR: [{ startsAt: null }, { startsAt: { lte: now } }] }, { OR: [{ endsAt: null }, { endsAt: { gte: now } }] }] }, orderBy: { position: "asc" } }),
    listProducts({ sort: "popular" }), listProducts({ condition: "REFURBISHED" }),
    db.category.findMany({ where: { isVisible: true, parentId: { not: null } }, include: { _count: { select: { products: true } } }, orderBy: [{ position: "asc" }, { name: "asc" }], take: 8 }),
    db.brand.findMany({ where: { isActive: true }, include: { _count: { select: { products: true } } }, orderBy: { name: "asc" }, take: 12 }),
    db.collection.findMany({ where: { isActive: true }, include: { products: { include: { product: { include: { brand: true, category: true, images: { take: 1, orderBy: { position: "asc" } }, variants: true, reviews: { where: { isVisible: true }, select: { rating: true } } } } }, take: 4 } }, orderBy: { createdAt: "asc" }, take: 4 }),
  ]);
  const visible = sections.length ? sections : [{ id: "hero", type: HomepageSectionType.HERO, title: "Certified tech, clearly priced", subtitle: null, config: null, position: 0, isVisible: true, storeId: store?.id ?? "", createdAt: now, updatedAt: now }, { id: "featured", type: HomepageSectionType.FEATURED_PRODUCTS, title: "Worth a closer look", subtitle: null, config: null, position: 1, isVisible: true, storeId: store?.id ?? "", createdAt: now, updatedAt: now }];
  return <>{visible.map((section) => {
    if (section.type === HomepageSectionType.HERO) { const banner = banners[0]; return <section className="hero" key={section.id}><div><p className="eyebrow">{section.title ?? "CERTIFIED TECH, CLEARLY PRICED"}</p><h1>Smart electronics.<br/><i>Seriously checked.</i></h1><p className="hero-copy">{section.subtitle ?? "Shop new, refurbished and pre-owned devices with honest condition grades, warranty coverage and doorstep delivery across India."}</p><div className="hero-actions"><Link className="primary-button" href="/products">Explore the catalog</Link><Link className="text-link" href="/products?condition=REFURBISHED">Shop refurbished →</Link></div><div className="hero-proof"><span><b>40-point</b> device inspection</span><span><b>6 months</b> refurbished warranty</span><span><b>{store?.settings?.returnDays ?? 7} days</b> easy returns</span></div></div><div className="hero-art"><div className="hero-shape"></div><img src={banner?.imageUrl ?? "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1000&q=85"} alt={banner?.title ?? "Modern smartphone in hand"}/></div></section>; }
    if (section.type === HomepageSectionType.CATEGORIES) return <section className="section" key={section.id}><div className="section-title"><div><p className="eyebrow">SHOP BY CATEGORY</p><h2>{section.title ?? "Everything electronic"}</h2></div></div><div className="category-grid">{categories.map((category) => <Link href={`/category/${category.slug}`} key={category.id}><b>{category.name}</b><small>{category._count.products} products</small></Link>)}</div></section>;
    if (section.type === HomepageSectionType.BRANDS) return <section className="brand-strip" key={section.id}><p className="eyebrow">{section.title ?? "POPULAR BRANDS"}</p><div>{brands.map((brand) => <Link href={`/products?brand=${brand.slug}`} key={brand.id}>{brand.name}<small>{brand._count.products}</small></Link>)}</div></section>;
    if (section.type === HomepageSectionType.COLLECTION) { const collection = collections[0]; if (!collection) return null; return <section className="section" key={section.id}><div className="section-title"><div><p className="eyebrow">CURATED COLLECTION</p><h2>{section.title && section.title !== "COLLECTION" ? section.title : collection.name}</h2></div><Link className="text-link" href={`/products?q=${encodeURIComponent(collection.name)}`}>Explore →</Link></div><div className="product-grid">{collection.products.map(({ product }) => <ProductCard key={product.id} product={product}/>)}</div></section>; }
    if (section.type === HomepageSectionType.FEATURED_PRODUCTS) return <section className="section" key={section.id}><div className="section-title"><div><p className="eyebrow">PICKED FOR YOU</p><h2>{section.title && section.title !== "FEATURED PRODUCTS" ? section.title : "Worth a closer look"}</h2></div><Link className="text-link" href="/products">View all products →</Link></div>{featured.length ? <div className="product-grid">{featured.slice(0, 4).map((product) => <ProductCard key={product.id} product={product}/>)}</div> : <div className="empty-state"><h3>The catalog is ready for publishing.</h3></div>}</section>;
    if (section.type === HomepageSectionType.PROMO_BANNER) { const banner = banners[1]; return banner ? <Link className="promo-banner" href={banner.linkUrl ?? "/products"} key={section.id}><img src={banner.imageUrl} alt=""/><span><b>{banner.title}</b><small>{banner.subtitle}</small></span></Link> : null; }
    if (section.type === HomepageSectionType.TRUST) return <section className="promise" key={section.id}><p className="eyebrow">THE REFURBSHIELD STANDARD</p><h2>{section.title && section.title !== "TRUST" ? section.title : "No guesswork. Just good gear."}</h2><div><article><b>01</b><h3>Checked in detail</h3><p>Every refurbished device is tested for performance, battery, display and connectivity before it is listed.</p></article><article><b>02</b><h3>Condition you can see</h3><p>New, refurbished and pre-owned are clearly labelled. There is no vague fine print.</p></article><article><b>03</b><h3>Support after checkout</h3><p>Protected payment verification, tracked order updates and a clear return route when you need it.</p></article></div></section>;
    return null;
  })}{refurbished.length > 0 && !visible.some((section) => section.type === HomepageSectionType.COLLECTION) && <section className="section"><h2>Certified refurbished</h2><div className="product-grid">{refurbished.slice(0,4).map((product) => <ProductCard key={product.id} product={product}/>)}</div></section>}</>;
}
