import { Role } from "@prisma/client";
import { NextRequest } from "next/server";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { apiError, AppError, json } from "@/lib/http";
import { z } from "zod";
const allowedTypes = new Set(["image/jpeg", "image/png", "image/webp", "image/avif"]);
export async function GET(request: NextRequest) { try { await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN, Role.PRODUCT_MANAGER]); return json(await db.mediaAsset.findMany({ orderBy: { createdAt: "desc" } })); } catch (error) { return apiError(error); } }
export async function POST(request: NextRequest) { try { await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN, Role.PRODUCT_MANAGER]); const supabaseUrl = process.env.SUPABASE_URL; const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY; const bucket = process.env.STORAGE_BUCKET; if (!supabaseUrl || !serviceKey || !bucket) throw new AppError(503, "Supabase Storage is not configured."); const form = await request.formData(); const file = form.get("file"); if (!(file instanceof File)) throw new AppError(400, "Choose an image to upload."); if (!allowedTypes.has(file.type)) throw new AppError(400, "Only JPEG, PNG, WebP and AVIF images are allowed."); if (file.size > 8 * 1024 * 1024) throw new AppError(413, "Image must be 8MB or smaller."); const store = await db.store.findFirstOrThrow(); const safeName = file.name.toLowerCase().replace(/[^a-z0-9._-]+/g, "-"); const path = `${store.id}/${Date.now()}-${crypto.randomUUID()}-${safeName}`; const upload = await fetch(`${supabaseUrl}/storage/v1/object/${bucket}/${path}`, { method: "POST", headers: { authorization: `Bearer ${serviceKey}`, apikey: serviceKey, "content-type": file.type, "x-upsert": "false" }, body: file }); if (!upload.ok) { console.error("Storage upload failed", upload.status, await upload.text()); throw new AppError(502, "Image upload failed."); } const url = `${supabaseUrl}/storage/v1/object/public/${bucket}/${path}`; const asset = await db.mediaAsset.create({ data: { storeId: store.id, name: file.name, url, mimeType: file.type, sizeBytes: file.size, alt: String(form.get("alt") ?? "") || null } }); return json(asset, 201); } catch (error) { return apiError(error); } }
export async function DELETE(request: NextRequest) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN, Role.PRODUCT_MANAGER]); const id = z.string().cuid().parse(new URL(request.url).searchParams.get("id")); const asset = await db.mediaAsset.findUnique({ where: { id } }); if (!asset) throw new AppError(404, "Media asset not found."); const supabaseUrl = process.env.SUPABASE_URL; const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY; const bucket = process.env.STORAGE_BUCKET; if (!supabaseUrl || !serviceKey || !bucket) throw new AppError(503, "Supabase Storage is not configured."); const prefix = `${supabaseUrl}/storage/v1/object/public/${bucket}/`; if (!asset.url.startsWith(prefix)) throw new AppError(409, "This asset is not stored in the configured bucket."); const path = asset.url.slice(prefix.length); const response = await fetch(`${supabaseUrl}/storage/v1/object/${bucket}/${path}`, { method: "DELETE", headers: { authorization: `Bearer ${serviceKey}`, apikey: serviceKey } }); if (!response.ok && response.status !== 404) throw new AppError(502, "Storage provider could not delete this image."); await db.$transaction([db.mediaAsset.delete({ where: { id } }), db.auditLog.create({ data: { actorId: admin.sub, action: "MEDIA_DELETED", entityType: "MediaAsset", entityId: id } })]); return json({ deleted: true }); } catch (error) { return apiError(error); } }
