import { ProductStatus, Prisma } from "@prisma/client";
import { cache } from "react";
import { db } from "@/lib/db";

export const productCardInclude = { brand: true, category: true, images: { orderBy: { position: "asc" as const }, take: 1 }, variants: { select: { id: true, stock: true, price: true, salePrice: true, title: true, attributes: true } }, reviews: { where: { isVisible: true }, select: { rating: true } } } satisfies Prisma.ProductInclude;
export type ProductFilters = { q?: string; category?: string; brand?: string; condition?: "NEW" | "REFURBISHED" | "USED"; min?: number; max?: number; availability?: boolean; storage?: string; ram?: string; color?: string; rating?: number; sort?: string };
export async function listProducts(input: string | ProductFilters = {}) {
  const filters = typeof input === "string" ? { q: input } : input;
  const orderBy: Prisma.ProductOrderByWithRelationInput = filters.sort === "price-asc" ? { salePrice: "asc" } : filters.sort === "price-desc" ? { salePrice: "desc" } : filters.sort === "popular" ? { orderItems: { _count: "desc" } } : filters.sort === "rating" ? { reviews: { _count: "desc" } } : { createdAt: "desc" };
  const attributeFilters = [filters.storage ? { attributes: { path: ["Storage"], equals: filters.storage } } : undefined, filters.ram ? { attributes: { path: ["RAM"], equals: filters.ram } } : undefined, filters.color ? { attributes: { path: ["Color"], equals: filters.color } } : undefined].filter(Boolean) as Prisma.ProductVariantWhereInput[];
  return db.product.findMany({ where: { status: ProductStatus.ACTIVE, deletedAt: null, condition: filters.condition, category: filters.category ? { slug: filters.category } : undefined, brand: filters.brand ? { slug: filters.brand } : undefined, basePrice: filters.min || filters.max ? { gte: filters.min, lte: filters.max } : undefined, reviews: filters.rating ? { some: { isVisible: true, rating: { gte: filters.rating } } } : undefined, variants: filters.availability || attributeFilters.length ? { some: { stock: filters.availability ? { gt: 0 } : undefined, AND: attributeFilters } } : undefined, ...(filters.q ? { OR: [{ name: { contains: filters.q, mode: "insensitive" } }, { sku: { contains: filters.q, mode: "insensitive" } }, { tags: { has: filters.q.toLowerCase() } }, { brand: { name: { contains: filters.q, mode: "insensitive" } } }, { category: { name: { contains: filters.q, mode: "insensitive" } } }, { variants: { some: { sku: { contains: filters.q, mode: "insensitive" } } } }] } : {}) }, include: productCardInclude, orderBy, take: 60 });
}
export const getProduct = cache(async (slug: string) => db.product.findFirst({ where: { slug, status: ProductStatus.ACTIVE, deletedAt: null }, include: { brand: true, category: true, images: { orderBy: { position: "asc" } }, variants: { orderBy: { title: "asc" } }, reviews: { where: { isVisible: true }, include: { user: { select: { name: true } } }, take: 10 } } }));
