import { OrderStatus, Role, ShipmentStatus } from "@prisma/client";
import { NextRequest } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { apiError, AppError, json } from "@/lib/http";
import { queueOrderNotification } from "@/lib/notifications/service";
const schema = z.object({ orderId: z.string().cuid(), courier: z.string().trim().min(2), trackingNumber: z.string().trim().min(3), trackingUrl: z.string().url().optional(), estimatedAt: z.string().datetime().optional() });
export async function POST(request: NextRequest) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN, Role.ORDER_MANAGER]); const input = schema.parse(await request.json()); const order = await db.order.findUnique({ where: { id: input.orderId } }); if (!order) throw new AppError(404, "Order not found."); if (order.status !== OrderStatus.PACKED && order.status !== OrderStatus.SHIPPED) throw new AppError(409, "Only packed orders can be shipped."); const shipment = await db.$transaction(async (tx) => { const result = await tx.shipment.upsert({ where: { orderId: order.id }, update: { courier: input.courier, trackingNumber: input.trackingNumber, trackingUrl: input.trackingUrl, estimatedAt: input.estimatedAt ? new Date(input.estimatedAt) : undefined, status: ShipmentStatus.SHIPPED, shippedAt: new Date() }, create: { orderId: order.id, courier: input.courier, trackingNumber: input.trackingNumber, trackingUrl: input.trackingUrl, estimatedAt: input.estimatedAt ? new Date(input.estimatedAt) : undefined, status: ShipmentStatus.SHIPPED, shippedAt: new Date() } }); if (order.status === OrderStatus.PACKED) await tx.order.update({ where: { id: order.id }, data: { status: OrderStatus.SHIPPED } }); await tx.auditLog.create({ data: { actorId: admin.sub, action: "SHIPMENT_CREATED", entityType: "Shipment", entityId: result.id, after: { courier: result.courier, trackingNumber: result.trackingNumber } } }); return result; }); await queueOrderNotification({ userId: order.userId, orderId: order.id, template: "ORDER_SHIPPED", payload: { orderNumber: order.orderNumber, courier: shipment.courier, trackingNumber: shipment.trackingNumber, trackingUrl: shipment.trackingUrl } }); return json(shipment, 201); } catch (error) { return apiError(error); } }
