import { Role } from "@prisma/client";
import { NextRequest } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { apiError, AppError, json } from "@/lib/http";
const schema = z.object({ id: z.string().cuid().optional(), name: z.string().trim().min(2), states: z.array(z.string()).default([]), pincodes: z.array(z.string().regex(/^\d{6}$/)).default([]), charge: z.number().int().min(0), freeShippingThreshold: z.number().int().min(0).optional(), estimatedDaysMin: z.number().int().positive(), estimatedDaysMax: z.number().int().positive(), priority: z.number().int().min(0).default(0), isActive: z.boolean().default(true) }).refine((value) => value.estimatedDaysMax >= value.estimatedDaysMin, { message: "Maximum estimate must be after minimum estimate." });
export async function POST(request: NextRequest) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN]); const input = schema.parse(await request.json()); const store = await db.store.findFirst(); if (!store) throw new AppError(409, "Store setup is incomplete."); const rule = await db.shippingRule.create({ data: { ...input, id: undefined, storeId: store.id } }); await db.auditLog.create({ data: { actorId: admin.sub, action: "SHIPPING_RULE_CREATED", entityType: "ShippingRule", entityId: rule.id } }); return json(rule, 201); } catch (error) { return apiError(error); } }
export async function PATCH(request: NextRequest) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN]); const input = schema.refine((value) => Boolean(value.id)).parse(await request.json()); const rule = await db.shippingRule.update({ where: { id: input.id! }, data: { name: input.name, states: input.states, pincodes: input.pincodes, charge: input.charge, freeShippingThreshold: input.freeShippingThreshold, estimatedDaysMin: input.estimatedDaysMin, estimatedDaysMax: input.estimatedDaysMax, priority: input.priority, isActive: input.isActive } }); await db.auditLog.create({ data: { actorId: admin.sub, action: "SHIPPING_RULE_UPDATED", entityType: "ShippingRule", entityId: rule.id } }); return json(rule); } catch (error) { return apiError(error); } }
export async function DELETE(request: NextRequest) { try { const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN]); const id = z.string().cuid().parse(new URL(request.url).searchParams.get("id")); await db.shippingRule.delete({ where: { id } }); await db.auditLog.create({ data: { actorId: admin.sub, action: "SHIPPING_RULE_DELETED", entityType: "ShippingRule", entityId: id } }); return json({ deleted: true }); } catch (error) { return apiError(error); } }
