import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Role } from "@prisma/client";
import { OrderActions } from "@/components/admin/order-actions";
import { currentSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { inr } from "@/lib/money";
import { validTransitions } from "@/lib/services/order-state";
export const dynamic = "force-dynamic";
export default async function AdminOrder({ params }: { params: Promise<{ id: string }> }) { const session = await currentSession(); const allowed: Role[] = [Role.SUPER_ADMIN, Role.ADMIN, Role.ORDER_MANAGER]; if (!session || !allowed.includes(session.role)) redirect("/login"); const order = await db.order.findUnique({ where: { id: (await params).id }, include: { user: true, items: true, payments: { include: { transactions: true } }, refunds: true, shipment: true } }); if (!order) notFound(); const address = order.shippingAddress as Record<string, string>; return <section className="admin-page"><Link className="text-link" href="/admin/orders">← Orders</Link><p className="eyebrow">{order.orderNumber}</p><h1>{order.status.replaceAll("_", " ")}</h1><div className="admin-two-col"><div><div className="admin-panel"><h2>Items</h2>{order.items.map((item) => <p className="line-summary" key={item.id}><span>{item.name}<small>{item.sku} × {item.quantity}</small></span><b>{inr(item.unitPrice * item.quantity)}</b></p>)}<hr/><p className="line-summary"><span>Subtotal</span><b>{inr(order.subtotal)}</b></p><p className="line-summary"><span>Discount</span><b>−{inr(order.discount)}</b></p>{order.cgstAmount > 0 && <p className="line-summary"><span>CGST</span><b>{inr(order.cgstAmount)}</b></p>}{order.sgstAmount > 0 && <p className="line-summary"><span>SGST</span><b>{inr(order.sgstAmount)}</b></p>}{order.igstAmount > 0 && <p className="line-summary"><span>IGST</span><b>{inr(order.igstAmount)}</b></p>}<p className="line-summary"><span>Shipping</span><b>{inr(order.shippingAmount)}</b></p><p className="line-summary"><strong>Total</strong><strong>{inr(order.total)}</strong></p></div><div className="admin-panel"><h2>Payment & refunds</h2>{order.payments.map((payment) => <p key={payment.id}>{payment.gateway} · {payment.status}<small>{payment.gatewayTransactionId ?? "No provider transaction yet"}</small></p>)}{order.refunds.map((refund) => <p key={refund.id}>Refund {inr(refund.amount)} · {refund.status}</p>)}</div></div><aside><div className="admin-panel"><h2>Customer</h2><p>{order.user?.name ?? "Guest checkout"}<small>{order.user?.email}</small></p><h3>Delivery address</h3><p>{address.name}<br/>{address.line1}<br/>{address.city}, {address.state} {address.pincode}<br/>{address.phone}</p>{order.shipment && <p><b>{order.shipment.courier}</b><br/>{order.shipment.trackingNumber}<br/>{order.shipment.status}</p>}</div><div className="admin-panel"><OrderActions orderId={order.id} transitions={(validTransitions[order.status] ?? []).map(String)} total={order.total} notes={order.internalNotes ?? ""} /></div></aside></div></section>; }
