import Link from "next/link";
import { redirect, notFound } from "next/navigation";
import { Role } from "@prisma/client";
import { currentSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { inr } from "@/lib/money";
import { CatalogCreateForm, CatalogRowEditor, InventoryAdjustForm, ReviewActions, SettingsForm, ShippingRuleForm, TaxRuleForm, UserAccessForm } from "@/components/admin/admin-controls";
import { MediaManager } from "@/components/admin/media-manager";
import { CouponActions, CouponCreate } from "@/components/admin/coupon-controls";
import { HomepageControls } from "@/components/admin/homepage-controls";
export const dynamic = "force-dynamic";
const allowed: Role[] = [Role.SUPER_ADMIN, Role.ADMIN, Role.PRODUCT_MANAGER, Role.ORDER_MANAGER];
export default async function AdminSection({ params }: { params: Promise<{ section: string }> }) { const session = await currentSession(); if (!session || !allowed.includes(session.role)) redirect("/login"); const section = (await params).section; let content: React.ReactNode; let title = section.replaceAll("-", " ");
  if (section === "categories") { const rows = await db.category.findMany({ include: { _count: { select: { products: true } } }, orderBy: { position: "asc" } }); const options = rows.map(({ id, name }) => ({ id, name })); content = <><CatalogCreateForm entity="categories" categories={options} /><table><thead><tr><th>Category</th><th>Slug</th><th>Products</th><th>Visible</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.slug}</td><td>{row._count.products}</td><td>{row.isVisible ? "Yes" : "No"}</td><td><CatalogRowEditor entity="categories" categories={options} value={row} /></td></tr>)}</tbody></table></>; }
  else if (section === "brands") { const rows = await db.brand.findMany({ include: { _count: { select: { products: true } } }, orderBy: { name: "asc" } }); content = <><CatalogCreateForm entity="brands" /><table><thead><tr><th>Brand</th><th>Slug</th><th>Products</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.slug}</td><td>{row._count.products}</td><td>{row.isActive ? "Active" : "Inactive"}</td><td><CatalogRowEditor entity="brands" value={{ ...row, imageUrl: row.logoUrl }} /></td></tr>)}</tbody></table></>; }
  else if (section === "collections") { const [rows, products] = await Promise.all([db.collection.findMany({ include: { products: { select: { productId: true } }, _count: { select: { products: true } } }, orderBy: { name: "asc" } }), db.product.findMany({ where: { deletedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } })]); content = <><CatalogCreateForm entity="collections" products={products} /><table><thead><tr><th>Collection</th><th>Slug</th><th>Products</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.slug}</td><td>{row._count.products}</td><td>{row.isActive ? "Active" : "Inactive"}</td><td><CatalogRowEditor entity="collections" products={products} value={{ ...row, productIds: row.products.map((item) => item.productId) }} /></td></tr>)}</tbody></table></>; }
  else if (section === "inventory") { const rows = await db.productVariant.findMany({ include: { product: true }, orderBy: { stock: "asc" } }); content = <><InventoryAdjustForm variants={rows.map((row) => ({ id: row.id, label: `${row.product.name} — ${row.title} (${row.sku})` }))} /><p><a className="secondary-button" href="/api/admin/inventory/export">Export inventory CSV</a></p><table><thead><tr><th>Product</th><th>Variant</th><th>SKU</th><th>Stock</th><th>Threshold</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.product.name}</td><td>{row.title}</td><td>{row.sku}</td><td>{row.stock}</td><td>{row.lowStockThreshold}</td></tr>)}</tbody></table></>; }
  else if (section === "customers") { const rows = await db.user.findMany({ where: { role: Role.CUSTOMER }, include: { _count: { select: { orders: true } } }, orderBy: { createdAt: "desc" } }); content = <table><thead><tr><th>Customer</th><th>Email</th><th>Orders</th><th>Joined</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.email}</td><td>{row._count.orders}</td><td>{row.createdAt.toLocaleDateString("en-IN")}</td></tr>)}</tbody></table>; }
  else if (section === "coupons") { const [rows, products, categories, collections] = await Promise.all([db.coupon.findMany({ orderBy: { createdAt: "desc" } }), db.product.findMany({ where: { deletedAt: null }, select: { id: true, name: true }, orderBy: { name: "asc" } }), db.category.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } }), db.collection.findMany({ select: { id: true, name: true }, orderBy: { name: "asc" } })]); content = <><CouponCreate products={products} categories={categories} collections={collections} /><table><thead><tr><th>Code</th><th>Type</th><th>Scope</th><th>Value</th><th>Minimum</th><th>Used</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.code}</td><td>{row.type}</td><td>{row.scopeType}</td><td>{row.type === "PERCENTAGE" ? `${row.value}%` : inr(row.value)}</td><td>{inr(row.minimumOrder ?? 0)}</td><td>{row.usedCount}</td><td>{row.isActive ? "Active" : "Inactive"}</td><td><CouponActions id={row.id} active={row.isActive} /></td></tr>)}</tbody></table></>; }
  else if (section === "reviews") { const rows = await db.review.findMany({ include: { user: true, product: true }, orderBy: { createdAt: "desc" } }); content = rows.length ? <table><thead><tr><th>Product</th><th>Customer</th><th>Rating</th><th>Verified</th><th>Visible</th><th>Moderate</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.product.name}</td><td>{row.user.name}</td><td>{row.rating}/5</td><td>{row.verifiedPurchase ? "Yes" : "No"}</td><td>{row.isVisible ? "Yes" : "Moderation"}</td><td><ReviewActions id={row.id} visible={row.isVisible} /></td></tr>)}</tbody></table> : <p>No reviews submitted yet.</p>; }
  else if (section === "payments") { const rows = await db.payment.findMany({ include: { order: true }, orderBy: { createdAt: "desc" } }); content = rows.length ? <table><thead><tr><th>Order</th><th>Gateway</th><th>Status</th><th>Amount</th><th>Created</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.order.orderNumber}</td><td>{row.gateway}</td><td>{row.status}</td><td>{inr(row.amount)}</td><td>{row.createdAt.toLocaleString("en-IN")}</td></tr>)}</tbody></table> : <p>No payment attempts yet.</p>; }
  else if (section === "shipping") { const rows = await db.shippingRule.findMany({ orderBy: { priority: "asc" } }); content = <><ShippingRuleForm /><table><thead><tr><th>Rule</th><th>Charge</th><th>Free over</th><th>Estimate</th><th>Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{inr(row.charge)}</td><td>{inr(row.freeShippingThreshold ?? 0)}</td><td>{row.estimatedDaysMin}–{row.estimatedDaysMax} days</td><td>{row.isActive ? "Active" : "Inactive"}</td></tr>)}</tbody></table></>; }
  else if (section === "tax") { const rows = await db.taxRule.findMany({ orderBy: { createdAt: "asc" } }); content = <><TaxRuleForm/><table><thead><tr><th>Rule</th><th>Rate</th><th>Home state</th><th>Interstate</th><th>Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.rate}%</td><td>{row.homeState}</td><td>IGST {row.rate}%</td><td>{row.isActive ? "Active" : "Inactive"}</td></tr>)}</tbody></table><p><small>For deliveries within {rows[0]?.homeState ?? "the home state"}, the configured GST is represented as equal CGST and SGST components. Interstate deliveries use IGST at the same combined rate.</small></p></>; }
  else if (section === "storefront") { const rows = await db.homepageSection.findMany({ orderBy: { position: "asc" } }); content = <><p><Link className="secondary-button" href="/admin/media">Open media library</Link></p><HomepageControls sections={rows.map((row) => ({ id: row.id, type: row.type, title: row.title ?? "", subtitle: row.subtitle ?? "", position: row.position, isVisible: row.isVisible }))} /></>; }
  else if (section === "media") { const rows = await db.mediaAsset.findMany({ orderBy: { createdAt: "desc" } }); content = <MediaManager assets={rows.map((row) => ({ id: row.id, name: row.name, url: row.url, alt: row.alt, mimeType: row.mimeType, sizeBytes: row.sizeBytes }))} configured={Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY && process.env.STORAGE_BUCKET)} />; }
  else if (section === "settings") { const store = await db.store.findFirst({ include: { settings: true } }); if (!store?.settings) content = <p>Settings have not been configured.</p>; else { const paymentConfig = (store.settings.paymentConfig ?? {}) as { razorpayEnabled?: boolean; phonePeEnabled?: boolean; snapmitEnabled?: boolean; sandboxMode?: boolean }; content = <SettingsForm value={{ storeName: store.name, currency: store.currency, supportEmail: store.settings.supportEmail ?? "", supportPhone: store.settings.supportPhone ?? "", logoUrl: store.settings.logoUrl ?? "", faviconUrl: store.settings.faviconUrl ?? "", gstin: store.settings.gstin ?? "", defaultTaxRate: store.settings.defaultTaxRate, freeShippingThreshold: store.settings.freeShippingThreshold, cancellationHours: store.settings.cancellationHours, returnDays: store.settings.returnDays, defaultGateway: store.settings.defaultGateway, razorpayEnabled: paymentConfig.razorpayEnabled ?? true, phonePeEnabled: paymentConfig.phonePeEnabled ?? false, snapmitEnabled: paymentConfig.snapmitEnabled ?? false, sandboxMode: paymentConfig.sandboxMode ?? true }} />; } }
  else if (section === "users") { const rows = await db.user.findMany({ orderBy: { createdAt: "desc" } }); content = <table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Access</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.name}</td><td>{row.email}</td><td>{row.role}</td><td>{row.isActive ? "Active" : "Disabled"}</td><td><UserAccessForm id={row.id} role={row.role} isActive={row.isActive} /></td></tr>)}</tbody></table>; }
  else if (section === "analytics") { const [paid, productGroups, categoryGroups, brandGroups, customerOrders, newCustomers] = await Promise.all([db.order.findMany({ where: { paymentStatus: "SUCCESS" }, select: { total: true, createdAt: true } }), db.orderItem.groupBy({ by: ["productId"], where: { order: { paymentStatus: "SUCCESS" } }, _sum: { quantity: true }, orderBy: { _sum: { quantity: "desc" } }, take: 10 }), db.orderItem.findMany({ where: { order: { paymentStatus: "SUCCESS" } }, select: { quantity: true, product: { select: { category: { select: { name: true } } } } } }), db.orderItem.findMany({ where: { order: { paymentStatus: "SUCCESS" } }, select: { quantity: true, product: { select: { brand: { select: { name: true } } } } } }), db.order.findMany({ where: { paymentStatus: "SUCCESS", userId: { not: null } }, select: { userId: true } }), db.user.count({ where: { role: Role.CUSTOMER, createdAt: { gte: new Date(new Date().getFullYear(), new Date().getMonth(), 1) } } })]); const products = await db.product.findMany({ where: { id: { in: productGroups.map((item) => item.productId) } }, select: { id: true, name: true } }); const names = new Map(products.map((item) => [item.id, item.name])); const sumBy = (items: { quantity: number; name: string }[]) => [...items.reduce((map, item) => map.set(item.name, (map.get(item.name) ?? 0) + item.quantity), new Map<string, number>())].sort((a, b) => b[1] - a[1]).slice(0, 8); const categories = sumBy(categoryGroups.map((item) => ({ quantity: item.quantity, name: item.product.category?.name ?? "Uncategorised" }))); const brands = sumBy(brandGroups.map((item) => ({ quantity: item.quantity, name: item.product.brand?.name ?? "Unbranded" }))); const customerCounts = customerOrders.reduce((map, order) => order.userId ? map.set(order.userId, (map.get(order.userId) ?? 0) + 1) : map, new Map<string, number>()); const repeat = [...customerCounts.values()].filter((count) => count > 1).length; const revenue = paid.reduce((sum, order) => sum + order.total, 0); content = <><div className="stat-grid"><article><span>Verified revenue</span><b>{inr(revenue)}</b></article><article><span>Average order value</span><b>{inr(paid.length ? Math.round(revenue / paid.length) : 0)}</b></article><article><span>New customers this month</span><b>{newCustomers}</b></article><article><span>Repeat customers</span><b>{repeat}</b></article></div><div className="dashboard-grid"><div><h3>Top products</h3>{productGroups.map((item) => <p className="rank-row" key={item.productId}><span>{names.get(item.productId)}</span><b>{item._sum.quantity ?? 0}</b></p>)}</div><div><h3>Top categories</h3>{categories.map(([name, quantity]) => <p className="rank-row" key={name}><span>{name}</span><b>{quantity}</b></p>)}</div><div><h3>Top brands</h3>{brands.map(([name, quantity]) => <p className="rank-row" key={name}><span>{name}</span><b>{quantity}</b></p>)}</div></div></>; }
  else if (section === "audit-logs") { const rows = await db.auditLog.findMany({ include: { actor: { select: { email: true } } }, orderBy: { createdAt: "desc" }, take: 100 }); content = rows.length ? <table><thead><tr><th>When</th><th>Admin</th><th>Action</th><th>Entity</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.createdAt.toLocaleString("en-IN")}</td><td>{row.actor?.email ?? "System"}</td><td>{row.action}</td><td>{row.entityType}</td></tr>)}</tbody></table> : <p>No audit events yet.</p>; }
  else notFound();
  return <section className="admin-page"><Link href="/admin" className="text-link">← Dashboard</Link><p className="eyebrow">ADMINISTRATION</p><h1>{title[0].toUpperCase() + title.slice(1)}</h1><div className="admin-panel">{content}</div></section>; }
