import { ProductCondition, ProductStatus, Role } from "@prisma/client";
import { NextRequest } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth";
import { parseCsv } from "@/lib/csv";
import { db } from "@/lib/db";
import { apiError, AppError, json } from "@/lib/http";
const rowSchema = z.object({ name: z.string().min(3), slug: z.string().regex(/^[a-z0-9-]+$/), sku: z.string().min(3), description: z.string().min(20), condition: z.nativeEnum(ProductCondition), basePriceINR: z.coerce.number().positive(), salePriceINR: z.union([z.literal(""), z.coerce.number().positive()]), categorySlug: z.string().min(1), brandSlug: z.string().min(1), variantTitle: z.string().min(1), variantSku: z.string().min(3), stock: z.coerce.number().int().nonnegative() });
type Row = z.infer<typeof rowSchema> & { sourceRow: number };
export async function POST(request: NextRequest) { try {
  const admin = await requireAdmin(request, [Role.SUPER_ADMIN, Role.ADMIN, Role.PRODUCT_MANAGER]); const text = await request.text(); if (text.length > 2_000_000) throw new AppError(413, "CSV file is too large."); const rows = parseCsv(text); if (rows.length < 2) throw new AppError(400, "CSV contains no product rows."); const headers = rows[0]; const errors: { row: number; message: string }[] = []; const valid: Row[] = [];
  rows.slice(1).forEach((values, index) => { const sourceRow = index + 2; const mapped = Object.fromEntries(headers.map((header, column) => [header, values[column] ?? ""])); const result = rowSchema.safeParse(mapped); if (!result.success) errors.push({ row: sourceRow, message: result.error.issues.map((issue) => `${issue.path.join(".")}: ${issue.message}`).join("; ") }); else valid.push({ ...result.data, sourceRow }); });
  if (errors.length) return json({ importedProducts: 0, importedVariants: 0, errors }, 422);
  const store = await db.store.findFirstOrThrow(); const [categories, brands, existingProducts, existingVariants] = await Promise.all([db.category.findMany({ where: { storeId: store.id } }), db.brand.findMany({ where: { storeId: store.id } }), db.product.findMany({ where: { OR: [{ sku: { in: valid.map((row) => row.sku) } }, { slug: { in: valid.map((row) => row.slug) } }] }, select: { sku: true, slug: true } }), db.productVariant.findMany({ where: { sku: { in: valid.map((row) => row.variantSku) } }, select: { sku: true } })]);
  const variantSkus = new Set<string>(); const groups = new Map<string, Row[]>();
  for (const row of valid) { if (!categories.some((item) => item.slug === row.categorySlug)) errors.push({ row: row.sourceRow, message: `Unknown category: ${row.categorySlug}` }); if (!brands.some((item) => item.slug === row.brandSlug)) errors.push({ row: row.sourceRow, message: `Unknown brand: ${row.brandSlug}` }); if (existingProducts.some((item) => item.sku === row.sku || item.slug === row.slug)) errors.push({ row: row.sourceRow, message: "Product SKU or slug already exists." }); if (existingVariants.some((item) => item.sku === row.variantSku) || variantSkus.has(row.variantSku)) errors.push({ row: row.sourceRow, message: `Variant SKU is duplicated: ${row.variantSku}` }); variantSkus.add(row.variantSku); const group = groups.get(row.sku) ?? []; const first = group[0]; if (first && ["name", "slug", "description", "condition", "basePriceINR", "salePriceINR", "categorySlug", "brandSlug"].some((key) => first[key as keyof Row] !== row[key as keyof Row])) errors.push({ row: row.sourceRow, message: `Product-level fields must match every row for SKU ${row.sku}.` }); group.push(row); groups.set(row.sku, group); }
  if (errors.length) return json({ importedProducts: 0, importedVariants: 0, errors }, 422);
  await db.$transaction(async (tx) => { for (const productRows of groups.values()) { const row = productRows[0]; const product = await tx.product.create({ data: { storeId: store.id, name: row.name, slug: row.slug, sku: row.sku, description: row.description, condition: row.condition, status: ProductStatus.ACTIVE, basePrice: Math.round(row.basePriceINR * 100), salePrice: row.salePriceINR === "" ? undefined : Math.round(row.salePriceINR * 100), categoryId: categories.find((item) => item.slug === row.categorySlug)!.id, brandId: brands.find((item) => item.slug === row.brandSlug)!.id, variants: { create: productRows.map((variant) => ({ title: variant.variantTitle, sku: variant.variantSku, stock: variant.stock })) } }, include: { variants: true } }); for (const [index, variant] of product.variants.entries()) await tx.inventoryTransaction.create({ data: { variantId: variant.id, quantityDelta: productRows[index].stock, previousStock: 0, resultingStock: productRows[index].stock, reason: "INITIAL_STOCK", reference: "CSV_IMPORT", actorId: admin.sub } }); await tx.auditLog.create({ data: { actorId: admin.sub, action: "PRODUCT_IMPORTED", entityType: "Product", entityId: product.id, after: { sku: product.sku, variants: product.variants.length } } }); } }, { timeout: 30_000 });
  return json({ importedProducts: groups.size, importedVariants: valid.length, errors: [] }, 201);
} catch (error) { return apiError(error); } }
